server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 60s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s # tempo para executar outra request
        enable-exponential-backoff: true # toda vez que uma request for feita, o tempo de espera ira aumantar exponencialmente
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: 1234
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    basu-url: http://localhost:9411
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include:
          - 'info'
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  swagger-ui:
    path: swagger
    configUrl: /book-service/v3/api-docs/swagger-config
    url: /book-service/v3/api-docs