server:
  port: 8080
spring:
  app:
    name: greeting-service
  config:
    import:
      - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - '*'
#          - 'refresh'
greeting-service:
  greeting: "Ola"
  default-value: "Mundo"
