server:
  port: 8888
spring:
  application:
    name: gusta-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gustavo-Angeli/microservices
          default-label: master
          search-paths:
            - 'secao-7-spring-cloud-configuration/code-gusta-config-server*'